### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by acherm** [fresnault/jhipster-chess-analysis#6]
I suggest to revise the installation instructions and the "workflow":
- maybe we should provide the schema/data of the database for the installation 
- bower install is mandatory to include all the JS stuff (in fact the website can be launched without "bower install" but then the Web page is simply a grey page) 
- I am not sure grunt has to be included/installed ?  
- the port is 8080 (not 3000)

**Comment by acherm** [comment]
This issue is mostly for internal usage and is not a top priority

**Comment by fresnault** [comment]
Hello Mathieu,

Yeah I need to retry the installation without nothing installed.
But if I'mnot mistaken : 
- The database will be created when we call maven command `mvn spring-boot:run`. But actually, only Jhipster logs are recorded, not articles.
- The bower file includes all JS libraries (https://github.com/fresnault/jhipster-chess-analysis/blob/master/bower.json) but some libraries are already in the repository (failed a commit). I will remove all bower_components libs.
- grunt should be installed with npm command (https://github.com/fresnault/jhipster-chess-analysis/blob/master/package.json). And if you run `grunt serve`, the application will be available at port 3000 with browser sync.

I understand the installation is not very easy, I will remake it and better.

**Comment by fresnault** [comment]
Readme file was updated !
https://github.com/fresnault/jhipster-chess-analysis/blob/5a88e77084af724c1a268a3fb0d992ec5d8bf6e8/README.md
